name: Pull Requests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@1819ae1a9b22c4a4264d0cc3922393291a0148c6 # v1
    secrets: inherit
    with:
      provider: lxd
