name: Release to latest/edge

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/renovate*"
      - ".github/workflows/release.yaml"
      - ".github/workflows/renovate.yaml"
      - ".github/workflows/update-libs.yaml"
      - ".gitignore"

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@1819ae1a9b22c4a4264d0cc3922393291a0148c6 # v1
    secrets: inherit
    with:
      provider: lxd