name: Auto-update Charm Libraries
on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"

jobs:
  update-lib:
    name: Check libraries
    uses: canonical/observability/.github/workflows/charm-update-libs.yaml@1819ae1a9b22c4a4264d0cc3922393291a0148c6 # v1
    secrets: inherit